
matching_configurations:
  brooklyn.nodes.Compute:
    capabilities:
      - host:
          properties:
            - num_cpus: { less_or_equal: 0 }
            - cpu_frequency: { less_or_equal: 0 Hz }
            - mem_size: { less_or_equal: 0 B }
            - disk_size: { less_or_equal: 0 B }
      - os:
          properties:
            - architecture: { equal: "" }
            - type: { equal: "" }
            - distribution: { equal: "" }
            - version: { less_or_equal: "" }